baseURL = "https://kkadikin.ru/"
languageCode = "ru-ru"
title = "Konstantin Kadikin Sm"
theme = "navigator-hugo"
copyright = "&copy; Creative Commons Attribution-ShareAlike 3.0 Unported"
publishDir = "docs"

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "ru"

# Site Params
[params]
    logo    = "images/logo.png"

    # Gestion des langues : RU / EN
    [[Params.listeLangues]]
    code = "ru"
    [[Params.listeLangues]]
    code = "en"

# Gestion des langues : RU / EN 
[Languages]
    ############ 1 - Site en RUSSIAN
    [Languages.ru]
    weight = 1
    languageCode = "ru-ru"
    title = "Konstantin Kadikin"
    dateFormat = "2 January 2006"

    home                    = "Домой"
    logo                    = "images/logo.png"
    menufixed               = false

    footerDescription       = "Мобильный телефон:"
    footerDescription_2     = "+7 921 359 34 37"
    footerDescription_3     = "E-mail:"
    footerDescription_4     = "kadikin@mail.ru"
    footerServiceTitle      = "Продукты"
    footerQuicklinkTitle    = "Быстрые ссылки"
    footerAboutTitle        = "Для связи"
    footerSubscribeTitle    = "Добро пожаловать"

    # Hero Area Section
    [Languages.ru.params.hero]
        enable              = true
        heading             = "Ваши капризы - наша забота"
        description         = "Всем привет, меня зовут Смайл." 
        description_2       = "Этот сайт посвящен системе Microsoft Power BI."
    # KK 01.06.2019 Убрано по комментариям, добавлю что-то позже
    #   description_3       = "К сожалению, основной контент сайта будет доступен на русском языке, так как с английским языком имеются проблемы :-)"
        button              = true
        btnText             = "Дополнительные сведения"
        btnURL              = "https://powerbi.microsoft.com/ru-ru/"
        videoThumb          = "/images/smile_main.png"
        videoURL            = "/images/smile_main_video_rus.mp4"

    # About 2 Section
    [Languages.ru.params.aboutSm]
        enable              = true
        title               = "С нездоровым энтузиазмом мы долгое время изучали систему Power BI"
        description         = "Что такое Power BI? <br> Power BI - это система аналитики, которая позволяет вам быстро оценить состояние вашего бизнеса для принятия управленческих решений. <br> На данный момент Power BI является развивающейся системой, функциональность которой постоянно расширяется."

    # Blog Section On Homepage
    [Languages.ru.params.blog]
        enable              = true
        topTitle            = "ЗАПИСКИ ОХОТНИКА"
        title               = "Блог"
        subtitle            = "Данный раздел содержит следующую информацию:"
        subtitle_2          = "короткие сообщения, тематические статьи, описание разработок."

    # Contact Section
    [Languages.ru.params.contact]
        enable              = true
        topTitle            = "ОСТАВЬТЕ СООБЩЕНИЕ"
        title               = "Контакты"
        subtitle            = "Приветствую, я постараюсь ответить на каждый вопрос как можно скорее. Пожалуйста, отправьте ваше сообщение на E-mail."
        titleaddress        = "Местонахождение"
        titlephone          = "Позвоните нам"
        titlemail           = "Напишите нам"
        address             = "Санкт-Петербург, <br> Россия"
        phone               = "Мобильный телефон: <br> +7 921 359 34 37"
        cityMap             = "/images/about/map-rus.jpg"
        contactFoto         = "/images/about/contact.jpg"
        mail                = "E-mail: <br> kadikin@mail.ru"

    # Call to Action Section on About Page
    [Languages.ru.params.cta]
        enable              = true
        bg                  = "images/call-to-action/background.jpg"
        title               = "Ключ на старт!"
        btnText             = "Контакты"
        btnURL              = "https://kkadikin.ru/ru/contact/"

    ############# 2 - Site ENGLISH
    [Languages.en]
    weight = 2
    languageCode = "en-us"
    title = "Konstantin Kadikin"
    dateFormat = "January 2, 2006"

    home                    = "Home"
    logo                    = "images/logo.png"
    menufixed               = false

    footerDescription       = "Mobile phone:"
    footerDescription_2     = "+7 921 359 34 37"
    footerDescription_3     = "E-mail:"
    footerDescription_4     = "kadikin@mail.ru"
    footerServiceTitle      = "Products"
    footerQuicklinkTitle    = "Quick links"
    footerAboutTitle        = "Contact us"
    footerSubscribeTitle    = "You are welcome"

    # Hero Area Section
    [Languages.en.params.hero]
        enable              = true
        heading             = "We always pander to your whims"
        description         = "Hello everyone, my name is Smile!"
        description_2       = "This site is dedicated to Microsoft Power BI system."
    # KK 01.06.2019 Убрано по комментариям, добавлю что-то позже
    #   description_3       = "Unfortunately, the basic content of the site will be available in Russian, because I have some problems with English :-)"
        button              = true
        btnText             = "Learn More"
        btnURL              = "https://powerbi.microsoft.com/en-us/"
        videoThumb          = "/images/smile_main.png"
        videoURL            = "/images/smile_main_video_eng.mp4"

    # About 2 Section
    [Languages.en.params.aboutSm]
        enable              = true
        title               = "We have explored Power BI system with unhealthy passion for a long time"
        description         = "What is Power BI? <br> Power BI is an Analytics system, that allows you to quickly assess the state of your business for management decisions. <br> At the moment, Power BI is an evolutionary system, the functionality of which is constantly expanding."

    # Blog Section On Homepage
    [Languages.en.params.blog]
        enable  = true
        topTitle= "HUNTER NOTES"
        title   = "Blog"
        subtitle            = "This section contains the following information:"
        subtitle_2          = "short messages, feature stories, description of developments."

    # Contact Section
    [Languages.en.params.contact]
        enable              = true
        topTitle            = "DROP US A NOTE"
        title               = "Contact Us"
        subtitle            = "Greetings, I will try to answer to your question as soon as possible. Please, send your message by E-mail."
        titleaddress        = "Location"
        titlephone          = "Call Us"
        titlemail           = "Write Us"
        address             = "St. Petersburg, <br> Russia"
        phone               = "Mobile phone: <br> +7 921 359 34 37"
        cityMap             = "/images/about/map-eng.jpg"
        contactFoto         = "/images/about/contact.jpg"
        mail                = "E-mail: <br> kadikin@mail.ru"

    # Call to Action Section on About Page
    [Languages.en.params.cta]
        enable              = true
        bg                  = "images/call-to-action/background.jpg"
        title               = "All systems go!"
        btnText             = "Contact Us"
        btnURL              = "https://kkadikin.ru/en/contact/"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = "Power_BI_Desktop"
        url     = "https://powerbi.microsoft.com/en-us/desktop/"
        weight  = 1
    [[menu.service]]
        name    = "Power_BI_Service"
        url     = "https://powerbi.microsoft.com/en-us/features/"
        weight  = 2
    [[menu.service]]
        name    = "Power_BI_Mobile"
        url     = "https://powerbi.microsoft.com/en-us/mobile/"
        weight  = 3

    # Footer Quick links Menu--
    [[menu.quicklink]]
        name    = "about"
        url     = "about"
        weight  = 1
    [[menu.quicklink]]
        name    = "service"
        url     = "service"
        weight  = 2
    [[menu.quicklink]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 3
    [[menu.quicklink]]
        name    = "blog"
        url     = "blog"
        weight  = 4
    [[menu.quicklink]]
        name    = "contact"
        url     = "contact"
        weight  = 5
